# -*- coding: utf-8 -*-
"""DATA 201 Capstone Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYS9Mx1xCOc8pcR-iaF9ZOD-76Ub0Xn_
"""

# DATA 201 CAPSTONE PROJECT
# How Insulin Use Affects Hospital Length of Stay

import pandas as pd
import matplotlib.pyplot as plt

# -------------------------
# Motivation
# -------------------------
# Hospital length of stay is a key driver of healthcare cost and patient outcomes.
# This project explores whether insulin use is associated with longer hospital stays.

url = "https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv"
df = pd.read_csv(url)

df.head()

# -------------------------
# Data Cleaning & Transformations
# -------------------------

# Keep valid genders
df = df[df['gender'].isin(['Male', 'Female'])].copy()

# Convert to numeric
df['time_in_hospital'] = pd.to_numeric(df['time_in_hospital'], errors='coerce')

# Drop missing values
df = df.dropna(subset=['time_in_hospital', 'insulin', 'age', 'num_medications', 'number_diagnoses'])

# Create insulin group
df = df[df['insulin'].isin(['Up','Down','Steady','No'])].copy()
df['insulin_group'] = df['insulin'].apply(lambda x: 'With Insulin' if x != 'No' else 'No Insulin')

# Convert age ranges to numeric midpoints
def age_mid(age_str):
    lo_hi = age_str.strip('[]()').replace(')', '').split('-')
    lo = int(lo_hi[0])
    hi = int(lo_hi[1])
    return (lo + hi) / 2

df['age_mid'] = df['age'].apply(age_mid)

df[['age','age_mid','insulin','insulin_group','time_in_hospital']].head()

# -------------------------
# Descriptive Statistics
# -------------------------
df['time_in_hospital'].describe()

# -------------------------
# Statistical Analysis: Correlation
# -------------------------
features = ['num_medications', 'num_lab_procedures', 'number_diagnoses']
corrs = df[features + ['time_in_hospital']].corr(numeric_only=True)['time_in_hospital']
corrs

# -------------------------
# Visualization 1: Length of stay by insulin group
# -------------------------
los_by_insulin = df.groupby('insulin_group')['time_in_hospital'].mean()

plt.figure()
plt.bar(los_by_insulin.index, los_by_insulin.values)
plt.title("Average Length of Stay by Insulin Use")
plt.xlabel("Insulin group")
plt.ylabel("Average days in hospital")
plt.show()

print("Interpretation of Graph 1:")
print("This bar chart compares the average length of hospital stay between patients who received insulin and those who did not. "
      "The higher average for the insulin group suggests that insulin use is associated with longer hospital stays.")
print()

# -------------------------
# Visualization 2: Medications by age and insulin
# -------------------------
df2 = df[df['age'].isin(['[30-40)', '[70-80)'])].copy()
pivot = df2.groupby(['age','insulin_group'])['num_medications'].mean().unstack()

pivot.plot(kind='bar')
plt.title("Average Number of Medications by Age and Insulin Use")
plt.xlabel("Age group")
plt.ylabel("Average number of medications")
plt.show()

print("Interpretation of Graph 2:")
print("This graph compares the average number of medications taken by patients in two age groups, ages 30–40 and 70–80, "
      "based on insulin use. The results suggest that older patients, especially those using insulin, tend to receive more medications.")
print()

# -------------------------
# Visualization 3: Medications vs Length of Stay
# -------------------------
plt.figure()
plt.scatter(df['num_medications'], df['time_in_hospital'])
plt.title("Number of Medications vs Length of Stay")
plt.xlabel("Number of medications")
plt.ylabel("Days in hospital")
plt.show()

print("Interpretation of Graph 3:")
print("This scatter plot shows the relationship between the number of medications and hospital length of stay. "
      "The general upward pattern suggests that patients taking more medications often remain in the hospital longer.")
print()

# -------------------------
# Visualization 4: Boxplot of hospital stay by insulin group
# -------------------------
plt.figure()
df.boxplot(column='time_in_hospital', by='insulin_group')
plt.title("Hospital Stay by Insulin Group")
plt.suptitle("")
plt.xlabel("Insulin Group")
plt.ylabel("Days in Hospital")
plt.show()

print("Interpretation of Graph 4:")
print("This boxplot compares the distribution of hospital stay for patients with and without insulin treatment. "
      "It highlights the median, spread, and possible outliers, showing that the insulin group tends to have a slightly higher and more variable hospital stay.")
print()

# -------------------------
# Visualization 5: Histogram of hospital stay by insulin group
# -------------------------
plt.figure()
df[df['insulin_group'] == 'With Insulin']['time_in_hospital'].hist(alpha=0.5, label='With Insulin')
df[df['insulin_group'] == 'No Insulin']['time_in_hospital'].hist(alpha=0.5, label='No Insulin')
plt.title("Distribution of Hospital Stay by Insulin Group")
plt.xlabel("Days in Hospital")
plt.ylabel("Frequency")
plt.legend()
plt.show()

print("Interpretation of Graph 5:")
print("This histogram shows the distribution of hospital stay for both insulin groups. "
      "It helps illustrate that patients receiving insulin appear more likely to have longer stays than patients not receiving insulin.")
print()

# -------------------------
# Visualization 6: Average age by insulin group
# -------------------------
age_by_insulin = df.groupby('insulin_group')['age_mid'].mean()

plt.figure()
plt.bar(age_by_insulin.index, age_by_insulin.values)
plt.title("Average Age by Insulin Group")
plt.xlabel("Insulin Group")
plt.ylabel("Average Age")
plt.show()

print("Interpretation of Graph 6:")
print("This graph compares the average age of patients who received insulin and those who did not. "
      "It suggests that insulin users may be older on average, which could partially explain why they also experience longer hospital stays.")
print()

# -------------------------
# Conclusion
# -------------------------
print("Conclusion:")
print("Patients who receive insulin stay in the hospital longer on average than patients who do not receive insulin. "
      "This suggests that insulin use may be associated with more complex or severe cases of diabetes. "
      "However, this analysis is correlational and the dataset does not directly measure disease severity.")

# -------------------------
# Statistical Analysis: Independent t-test
# -------------------------
from scipy.stats import ttest_ind

# Separate the two groups
with_insulin = df[df['insulin_group'] == 'With Insulin']['time_in_hospital']
no_insulin = df[df['insulin_group'] == 'No Insulin']['time_in_hospital']

# Perform Welch's t-test
t_stat, p_value = ttest_ind(with_insulin, no_insulin, equal_var=False)

print("T-test Results")
print("t-statistic:", round(t_stat, 3))
print("p-value:", p_value)

if p_value < 0.05:
    print("There is a statistically significant difference in hospital length of stay between patients who use insulin and those who do not.")
else:
    print("There is no statistically significant difference in hospital length of stay between the two groups.")

# -------------------------
# Statistical Analysis: Correlation between age and hospital stay
# -------------------------

correlation = df['age_mid'].corr(df['time_in_hospital'])

print("Correlation between age and time in hospital:", round(correlation, 3))

if correlation > 0:
    print("Older patients tend to stay longer in the hospital.")
elif correlation < 0:
    print("Older patients tend to stay fewer days in the hospital.")
else:
    print("There is no relationship between age and time in hospital.")

# -------------------------
# Statistical Summary by Insulin Group
# -------------------------

stats = df.groupby('insulin_group')['time_in_hospital'].agg(['mean', 'std', 'count'])

print(stats)

# Save values for easier reading
mean_no = stats.loc['No Insulin', 'mean']
mean_yes = stats.loc['With Insulin', 'mean']

std_no = stats.loc['No Insulin', 'std']
std_yes = stats.loc['With Insulin', 'std']

count_no = stats.loc['No Insulin', 'count']
count_yes = stats.loc['With Insulin', 'count']

print("\nConclusion:")
print(
    f"Patients who received insulin stayed in the hospital an average of "
    f"{mean_yes:.2f} days, compared to {mean_no:.2f} days for patients who did not receive insulin. "
    f"The insulin group also had slightly more variation in hospital stay "
    f"({std_yes:.2f} vs {std_no:.2f}), suggesting these patients may have more complex medical conditions. "
    f"The analysis included {count_yes:,} patients with insulin and {count_no:,} patients without insulin."
)